Support ICU library provided by Windows 10 + Preset updates
EasyRPG/liblcf pull request #486
Opened 2024-10-10 12:10 UTC by Ghabry

Ported the normalization code to the ICU C-API so looks more ugly now :sweat_smile: but C++ has no stable ABI so Microsoft decided to only provide the C part.

This _does not_ remove 3rd party ICU support. When a custom ICU library is found it has preference.

Rest is just updating of presets based on Player preset updates.

---

For now I plan to keep using the vcpkg ICU library but when I do not want to maintain this anymore I can now simply drop it.

2024-10-11 02:36 UTC, fdelapena approved these changes

2024-10-12 10:15 UTC, carstene1ns commented
Something is failing here with function renaming across multiple ICU versions.
Maybe some inclusion order of headers or something?

2024-10-12 10:47 UTC, carstene1ns requested changes

2024-10-12 10:47 UTC, carstene1ns commented on src/reader_util.cpp
>  #   include <unicode/locid.h>
`unistr.h` is c++ api

```suggestion
#   include <unicode/ustring.h>
```

2024-10-12 10:47 UTC, carstene1ns commented on src/reader_util.cpp
> +		Log::Error("%s failed while normalizing \"%s\": %s", std::string(str).c_str(), u_errorName(err));
```suggestion
	auto log_warning = [err, &str](const char *func_name) {
		Log::Error("%s failed while normalizing \"%s\": %s", func_name, std::string(str).c_str(), u_errorName(err));
```

2024-10-14 16:41 UTC, Ghabry commented
thanks for the fixes c1, added them

2024-10-14 20:34 UTC, carstene1ns approved these changes

2024-10-14 20:34 UTC, merged